auth_service:
  client_id: "Xrp13uyF2pm340DskCRSnpeiJZlyGAjq"
  client_secret: "dWfRUYQxMr40kGgNB8Q4Obq43cc1tGt3c_NxIY4F_GLlp-Ov78p4J5XH4zKd6Eit"
service:
  port: 8080
  environment: dev
  log_file_path: "."
  log_file_name: "authentiction_service.log"
database:
  host: db
  username: postgres
  password: Netlink412001!
  dbname: auth_db
  port: 5432